version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    networks:
      - sonarqube-network
    volumes:
      - sonarqube-data:/opt/sonarqube/data

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    networks:
      - sonarqube-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  sonarqube-network:

volumes:
  sonarqube-data:
  postgres-data:

