---
urls-list:
    - http://www.adidas.com/us/
    - http://www.nike.com/us/en_us/
    - http://www.supremenewyork.com/
    - http://www.footlocker.com/
    - http://www.eastbay.com/
    - http://www.footaction.com/
    - http://www.finishline.com/
    - http://www.champssports.com/
    - https://us.bape.com/










